#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  baseContact: 
    type: object
    discriminator: contactDetailType
    properties:
      id:
        (annotations.supportedIn):
          - country: PE
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Contact information identifier.
        required: false
      contactDetailType:
        (annotations.supportedIn):
          - country: PE
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        enum: [EMAIL, MOBILE]
        (annotations.enumDescription):
          - EMAIL: Email contact. 
          - MOBILE: Mobile phone contact.
        description: |
          Contact information type.
        required: false