#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  campaign:
    type: object
    properties:
      code:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Campaign code.
        required: false
