#%RAML 1.0 Library
uses:
  annotations:  ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
 
types:
  dictumReasons:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: POST
            input: NONE
            output: REQUIRED
        type: string
        description: |
          Identifier of the reason of dictum.
        required: false
      description:
        (annotations.bindingDefinition):
          - method: POST
            input: NONE
            output: REQUIRED
        type: string
        description: |
          Description of the reason of dictum.
        required: false