#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
  baseContact: baseContact.raml
  phoneCompany: phoneCompany.raml

types:
  mobile:
    type: baseContact.baseContact
    discriminatorValue: MOBILE
    description: Mobile contact type
    properties:
      number:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: |
          Contact mobile number. This value will be masked when basic
          authentication state. If the authentication state is advanced the
          value will be clear.          
      phoneCompany:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: phoneCompany.phoneCompany
        description: |
          Contact vendor information.
        required: false
