#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

  operationType: operationType.raml

types:
  operation:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "NONE"
        type: string
        description: |
          Identifier of the operation that allows an intercompany relationship.
        required: false
      operationType:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "NONE"
        type: operationType.operationType
        description: |
          Operation type to obtain an external product.
        required: false
