#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  operationType:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "NONE"
        type: string
        description: |
          Identifier of the type of operation to obtain an external product.
        required: false
      name:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
        type: string
        description: |
          Description of the type of operation to obtain an external product.
        required: false
