#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  phoneCompany:
    type: object
    required: false
    properties:
      id:
        (annotations.supportedIn):
          - country: PE
        (annotations.bindingDefinition):
          - method : "POST"
            input : "REQUIRED"
            output : "REQUIRED"
          - method : "GET"
            input : "NONE"
            output : "REQUIRED" 
        type: string
        description: |
          Cellphone company identifier.
        required: false
      name:
        (annotations.supportedIn):
          - country: PE
        (annotations.bindingDefinition):
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
          - method : "GET"
            input : "NONE"
            output : "REQUIRED"
        type: string
        description: |
          Cellphone company name.
        required: false
