#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  productConfiguration:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Product configuration identifier.
        required: false
      description:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Product configuration description.
        required: false
