#%RAML 1.0 Library
uses:
  annotations: ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  riskLevel:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Risk level identifier.
        required: false
      name:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: string
        description: |
          Risk level description.
        required: false
